#pragma once

// Simplify operator overloading for strong types.
// [Operator Overloading](https://en.cppreference.com/w/cpp/language/operators)

#define STRONG_INFIX_OPERATOR(TYPE, OP) \
    template <typename TYPE> \
    auto operator OP(TYPE a, TYPE b) { \
        return a.value OP b.value; \
    }

#define STRONG_PREFIX_OPERATOR(TYPE, OP) \
    template <typename TYPE> \
    auto operator OP(TYPE a) { \
        return OP a.value; \
    }

#define STRONG_POSTFIX_OPERATOR(TYPE, OP) \
    template <typename TYPE> \
    auto operator OP(TYPE a, int) { \
        return a.value OP; \
    }

#define STRONG_ARITHMETIC_OPERATORS(TYPE) \
    STRONG_INFIX_OPERATOR(TYPE, +) \
    STRONG_INFIX_OPERATOR(TYPE, -) \
    STRONG_INFIX_OPERATOR(TYPE, *) \
    STRONG_INFIX_OPERATOR(TYPE, /) \
    STRONG_PREFIX_OPERATOR(TYPE, +) \
    STRONG_PREFIX_OPERATOR(TYPE, -)

#define STRONG_COMPARISON_OPERATORS(TYPE) \
    STRONG_INFIX_OPERATOR(TYPE, ==) \
    STRONG_INFIX_OPERATOR(TYPE, !=) \
    STRONG_INFIX_OPERATOR(TYPE, >) \
    STRONG_INFIX_OPERATOR(TYPE, <) \
    STRONG_INFIX_OPERATOR(TYPE, >=) \
    STRONG_INFIX_OPERATOR(TYPE, <=)

#define STRONG_INCREMENT_DECREMENT_OPERATORS(TYPE) \
    STRONG_PREFIX_OPERATOR(TYPE, ++) \
    STRONG_PREFIX_OPERATOR(TYPE, --) \
    STRONG_POSTFIX_OPERATOR(TYPE, ++) \
    STRONG_POSTFIX_OPERATOR(TYPE, --)

// Short-circit evaluation is lost for overloaded operators && and ||
#define STRONG_LOGICAL_OPERATORS(TYPE) \
    STRONG_INFIX_OPERATOR(TYPE, &&) \
    STRONG_INFIX_OPERATOR(TYPE, ||) \
    STRONG_PREFIX_OPERATOR(TYPE, ! )

#define STRONG_BITWISE_OPERATORS(TYPE) \
    STRONG_INFIX_OPERATOR(TYPE, &) \
    STRONG_INFIX_OPERATOR(TYPE, |) \
    STRONG_INFIX_OPERATOR(TYPE, ^) \
    STRONG_PREFIX_OPERATOR(TYPE, ~)

#define STRONG_ARITHMETIC_ASSIGNMENT_OPERATORS(TYPE) \
    STRONG_INFIX_OPERATOR(TYPE, +=) \
    STRONG_INFIX_OPERATOR(TYPE, -=) \
    STRONG_INFIX_OPERATOR(TYPE, *=) \
    STRONG_INFIX_OPERATOR(TYPE, /=)

#define STRONG_BITWISE_ASSIGNMENT_OPERATORS(TYPE) \
    STRONG_INFIX_OPERATOR(TYPE, &=) \
    STRONG_INFIX_OPERATOR(TYPE, |=) \
    STRONG_INFIX_OPERATOR(TYPE, ^=)

#define STRONG_INTEGRAL_OPERATORS(TYPE) \
    STRONG_ARITHMETIC_OPERATORS(TYPE) \
    STRONG_COMPARISON_OPERATORS(TYPE) \
    STRONG_INCREMENT_DECREMENT_OPERATORS(TYPE) \
    STRONG_LOGICAL_OPERATORS(TYPE) \
    STRONG_BITWISE_OPERATORS(TYPE) \
    STRONG_ARITHMETIC_ASSIGNMENT_OPERATORS(TYPE) \
    STRONG_BITWISE_ASSIGNMENT_OPERATORS(TYPE)

#define STRONG_FLOATING_POINT_OPERATORS(TYPE) \
    STRONG_ARITHMETIC_OPERATORS(TYPE) \
    STRONG_COMPARISON_OPERATORS(TYPE) \
    STRONG_ARITHMETIC_ASSIGNMENT_OPERATORS(TYPE)
