---
name: Continuous Integration

on: [push]

jobs:

  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    env:
      REGISTRY: ghcr.io
      IMAGE: ${{github.repository}}

    steps:

      - name: Login
        uses: docker/login-action
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Metadata
        id: meta
        uses: docker/metadata-action
        with:
          images: ${{env.REGISTRY}}/${{env.IMAGE}}

      - name: Build and Push
        id: push
        uses: docker/build-and-push-action
        with:
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}

      - name: Attestation
        uses: actions/attest-build-provenance
        with:
          subject-name: ${{env.REGISTRY}}/${{env.IMAGE}}
          subject-digest: ${{steps.push.outpus.digest}}
          push-to-registry: true

  build:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/tmparks/cpp
    strategy:
      matrix:
        build: [Release, Debug]   # Build type
        std: [11, 14, 17, 20, 23] # C++ standard

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build and Test
      env:
        CMAKE_OPTIONS: >-
          -DCMAKE_BUILD_TYPE=${{matrix.build}}
          -DCMAKE_CXX_STANDARD=${{matrix.std}}
          -DCMAKE_COMPILE_WARNING_AS_ERROR=YES
      run: |
        lscpu
        cmake $CMAKE_OPTIONS -S . -B build
        make --directory=build all
        /usr/bin/time --verbose build/TestRunner

    - name: Coverage
      if: ${{matrix.build == 'Debug'}}
      run: make --directory=build coverage

    - name: Upload Artifacts
      if: ${{matrix.build == 'Debug'}}
      uses: actions/upload-artifact@v4
      with:
        name: coverage-${{matrix.std}}
        path: build/results/

    - name: Check
      run: |
        cmake -DCMAKE_COMPILE_WARNING_AS_ERROR=NO build
        make --directory=build check

...
