# [GitHub Actions documentation](https://docs.github.com/en/actions)
---
name: Continuous Integration

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE: ${{github.repository}}
  TAG: latest

jobs:

  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and Push
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{env.REGISTRY}}/${{env.IMAGE}}:${{env.TAG}}

  build:
    needs: docker
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tmparks/cpp:latest
    strategy:
      matrix:
        build: [Release, Debug]   # Build type
        std: [11, 14, 17, 20, 23] # C++ standard

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build and Test
      env:
        CMAKE_OPTIONS: >-
          -DCMAKE_BUILD_TYPE=${{matrix.build}}
          -DCMAKE_CXX_STANDARD=${{matrix.std}}
          -DCMAKE_COMPILE_WARNING_AS_ERROR=YES
      run: |
        lscpu
        cmake $CMAKE_OPTIONS -S . -B build
        make --directory=build all
        /usr/bin/time --verbose build/TestRunner

    - name: Coverage
      if: ${{matrix.build == 'Debug'}}
      run: make --directory=build coverage

    - name: Upload Artifacts
      if: ${{matrix.build == 'Debug'}}
      uses: actions/upload-artifact@v4
      with:
        name: coverage-${{matrix.std}}
        path: build/results/

    - name: Check
      run: |
        cmake -DCMAKE_COMPILE_WARNING_AS_ERROR=NO build
        make --directory=build check

...
