---
name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/tmparks/cpp
    strategy:
      matrix:
        build: [Release, Debug]   # Build type
        std: [11, 14, 17, 20, 23] # C++ standard

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      env:
        CMAKE_OPTIONS: >-
          -DCMAKE_BUILD_TYPE=${{matrix.build}}
          -DCMAKE_CXX_STANDARD=${{matrix.std}}
          -DCMAKE_COMPILE_WARNING_AS_ERROR=YES
      run: cmake $CMAKE_OPTIONS -S . -B build

    - name: Build
      run: make --directory=build all

    - name: Test
      if: ${{matrix.std >= 17}}
      run: |
        lscpu
        /usr/bin/time --verbose build/TestRunner

    - name: Coverage
      if: ${{matrix.build == 'Debug' && matrix.std >= 17}}
      run: make --directory=build coverage

    - name: Upload Artifacts
      if: ${{matrix.build == 'Debug'}}
      uses: actions/upload-artifact@v4
      with:
        name: coverage-${{matrix.std}}
        path: build/results/

    - name: Check
      run: |
        cmake -DCMAKE_COMPILE_WARNING_AS_ERROR=NO build
        make --directory=build check

...
