name: CMake on a single platform

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/tmparks/cpp
    strategy:
      matrix:
        build: [Release, Debug]   # Build type
        std: [11, 14, 17, 20, 23] # C++ standard

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      env:
        CMAKE_BUILD_TYPE: ${{matrix.build}}
        CMAKE_CXX_STANDARD: ${{matrix.std}}
        CXXFLAGS: -Werror
      run: cmake -S . -B build

    - name: Build
      run: make --directory=build all

    - name: Test
      run: /usr/bin/time --verbose build/TestRunner

    - name: Coverage
      if: ${{matrix.build == Debug}}
      run: make --directory=build coverage

    - name: Check
      if: ${{matrix.build == Debug}}
      run: make --directory=build check
